### ISSUE TITLE
In a visualization with several layers, infowindow from a layer is appearing with "no data available" because infowindow data is incorrect from layer definition

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#713]
https://github.com/CartoDB/cartodb/issues/5917

**Comment by alonsogarciapablo** [comment]
The fix is now working :(.

## STR

1. Create a map using the editor with a couple of layers.
2. Enable infowindows and tooltips in the layer that is on top (#2).
3. Hide the layer that is at the bottom (#1).
4. Go to the embedded map.

## Expected results
- Tooltips/Infowindows work.

## Actual results
- Looks like interaction is disabled.

# Possible solution

I think we should use the real indexes [here](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/layer_definition.js#L650-L674) (what the `layer` variable instead of using `this.getLayerNumberByIndex`), and I think we should only enable interactivity [here](https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/vis.js#L1170-L1176) if the layer is visible, otherwise it messes up everything.

**Comment by alonsogarciapablo** [comment]
Branch with previous solution is [here](https://github.com/CartoDB/cartodb.js/tree/issue-713).

**Comment by smetrick** [comment]
New to Github. I was at least partially responsible for flagging this issue. When I published my first map at http://cdb.io/1Kvz18u clicking on a parcel feature returns no data. When I log into my Cartodb account, this function works just fine. Que pasa?

**Comment by alonsogarciapablo** [comment]
@smetrick please check out [this issue](https://github.com/CartoDB/cartodb/issues/5917) for more context.

**Comment by acanimal** [comment]
@smetrick Could you confirm the error persists? If so, can you describe me the exact steps to reproduce the error. Thanks.

**Comment by smetrick** [comment]
The error no longer occurs. I believe it was solved by reviewing and changing my layer display properties.
It was not clear at first to me this step was necessary, as this is my first map.

**Comment by acanimal** [comment]
Thanks, so I will close the ticket.
